//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACME.POS.Service.DataTypes
{


    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ACME.POS.Service.DataTypes/2007/06", IsNullable = false)]
    public class State
    {

        private string abbrv;

        private string name;

        public string Abbrv
        {
            get
            {
                return this.abbrv;
            }
            set
            {
                this.abbrv = value;
            }
        }

        public string Name
        {
            get
            {
                return this.name;
            }
            set
            {
                this.name = value;
            }
        }
    }
}

