//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGTEL.SampleAB.Configuration.Design.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DGTEL.SampleAB.Configuration.Design.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add SampleAB.
        /// </summary>
        internal static string AddDGTEL_SampleAB {
            get {
                return ResourceManager.GetString("AddDGTEL_SampleAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddMath.
        /// </summary>
        internal static string AddMathName {
            get {
                return ResourceManager.GetString("AddMathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add AddMath Provider.
        /// </summary>
        internal static string AddMathUICommandLongText {
            get {
                return ResourceManager.GetString("AddMathUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add AddMath Provider.
        /// </summary>
        internal static string AddMathUICommandText {
            get {
                return ResourceManager.GetString("AddMathUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string CategoryGeneral {
            get {
                return ResourceManager.GetString("CategoryGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomMath.
        /// </summary>
        internal static string CustomMathName {
            get {
                return ResourceManager.GetString("CustomMathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Custom Math.
        /// </summary>
        internal static string CustomMathUICommandLongText {
            get {
                return ResourceManager.GetString("CustomMathUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Custom Math.
        /// </summary>
        internal static string CustomMathUICommandText {
            get {
                return ResourceManager.GetString("CustomMathUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the default math provider..
        /// </summary>
        internal static string DefaultMathDescription {
            get {
                return ResourceManager.GetString("DefaultMathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SampleAB.
        /// </summary>
        internal static string DGTEL_SampleAB {
            get {
                return ResourceManager.GetString("DGTEL_SampleAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math.
        /// </summary>
        internal static string MathName {
            get {
                return ResourceManager.GetString("MathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the MathUICommandLongText resource value.
        /// </summary>
        internal static string MathUICommandLongText {
            get {
                return ResourceManager.GetString("MathUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the MathUICommandText resource value.
        /// </summary>
        internal static string MathUICommandText {
            get {
                return ResourceManager.GetString("MathUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubtractMath.
        /// </summary>
        internal static string SubtractMathName {
            get {
                return ResourceManager.GetString("SubtractMathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add SubtractMath Provider.
        /// </summary>
        internal static string SubtractMathUICommandLongText {
            get {
                return ResourceManager.GetString("SubtractMathUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add SubtractMath Provider.
        /// </summary>
        internal static string SubtractMathUICommandText {
            get {
                return ResourceManager.GetString("SubtractMathUICommandText", resourceCulture);
            }
        }
    }
}
