//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACME.POS.Service.ServiceContracts
{


    // IMPORTANT: The Namespace parameter of the System.Web.Services.WebService attribute cannot be used to control the XML Namespace of Web Service interfaces. The attribute must be applied to a class which implements the service contract interface.
    [System.Web.Services.WebService(Namespace = "http://ACME.POS.Service.ServiceContracts/2007/06", Name = "Customer")]
    [System.Web.Services.WebServiceBindingAttribute(ConformsTo = System.Web.Services.WsiProfiles.BasicProfile1_1, EmitConformanceClaims = true, Name = "Customer")]
    public interface ICustomer
    {

        [System.Web.Services.WebMethodAttribute(MessageName = "GetCustomerList")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute(Action = "http://ACME.POS.Service.ServiceContracts/2007/06/GetCustomerList", ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        ACME.POS.Service.DataTypes.Customer[] GetCustomerList();

        [System.Web.Services.WebMethodAttribute(MessageName = "SaveCustomer")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute(Action = "http://ACME.POS.Service.ServiceContracts/2007/06/SaveCustomer", ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        ACME.POS.Service.DataTypes.Customer SaveCustomer(ACME.POS.Service.DataTypes.Customer SaveCustomerRequest);
    }
}

