//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.312.
// 
#pragma warning disable 1591

namespace ACME.POS.Service.Client.ACMECustomerWebService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Customer", Namespace="http://ACME.POS.Service.ServiceContracts/2007/06")]
    public partial class CustomerServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCustomerListOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveCustomerOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CustomerServices() {
            this.Url = global::ACME.POS.Service.Client.Properties.Settings.Default.ACME_POS_Service_Client_ACMECustomerWebService_Customer;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCustomerListCompletedEventHandler GetCustomerListCompleted;
        
        /// <remarks/>
        public event SaveCustomerCompletedEventHandler SaveCustomerCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ACME.POS.Service.ServiceContracts/2007/06/GetCustomerList", RequestNamespace="http://ACME.POS.Service.ServiceContracts/2007/06", ResponseNamespace="http://ACME.POS.Service.ServiceContracts/2007/06", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Customer[] GetCustomerList() {
            object[] results = this.Invoke("GetCustomerList", new object[0]);
            return ((Customer[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerListAsync() {
            this.GetCustomerListAsync(null);
        }
        
        /// <remarks/>
        public void GetCustomerListAsync(object userState) {
            if ((this.GetCustomerListOperationCompleted == null)) {
                this.GetCustomerListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerListOperationCompleted);
            }
            this.InvokeAsync("GetCustomerList", new object[0], this.GetCustomerListOperationCompleted, userState);
        }
        
        private void OnGetCustomerListOperationCompleted(object arg) {
            if ((this.GetCustomerListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerListCompleted(this, new GetCustomerListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ACME.POS.Service.ServiceContracts/2007/06/SaveCustomer", RequestNamespace="http://ACME.POS.Service.ServiceContracts/2007/06", ResponseNamespace="http://ACME.POS.Service.ServiceContracts/2007/06", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://ACME.POS.Service.DataTypes/2007/06")]
        public Customer SaveCustomer([System.Xml.Serialization.XmlElementAttribute(Namespace="http://ACME.POS.Service.DataTypes/2007/06")] Customer SaveCustomerRequest) {
            object[] results = this.Invoke("SaveCustomer", new object[] {
                        SaveCustomerRequest});
            return ((Customer)(results[0]));
        }
        
        /// <remarks/>
        public void SaveCustomerAsync(Customer SaveCustomerRequest) {
            this.SaveCustomerAsync(SaveCustomerRequest, null);
        }
        
        /// <remarks/>
        public void SaveCustomerAsync(Customer SaveCustomerRequest, object userState) {
            if ((this.SaveCustomerOperationCompleted == null)) {
                this.SaveCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveCustomerOperationCompleted);
            }
            this.InvokeAsync("SaveCustomer", new object[] {
                        SaveCustomerRequest}, this.SaveCustomerOperationCompleted, userState);
        }
        
        private void OnSaveCustomerOperationCompleted(object arg) {
            if ((this.SaveCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveCustomerCompleted(this, new SaveCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ACME.POS.Service.DataTypes/2007/06")]
    public partial class Customer {
        
        private int customerIdField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private System.DateTime memberSinceField;
        
        private System.DateTime birthDateField;
        
        private Address[] addressesField;
        
        private BillingMethod[] billingMethodsField;
        
        private bool isActiveField;
        
        private bool isModifiedField;
        
        /// <remarks/>
        public int CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime MemberSince {
            get {
                return this.memberSinceField;
            }
            set {
                this.memberSinceField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        public Address[] Addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
            }
        }
        
        /// <remarks/>
        public BillingMethod[] BillingMethods {
            get {
                return this.billingMethodsField;
            }
            set {
                this.billingMethodsField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public bool IsModified {
            get {
                return this.isModifiedField;
            }
            set {
                this.isModifiedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ACME.POS.Service.DataTypes/2007/06")]
    public partial class Address {
        
        private int addressIdField;
        
        private int customerIdField;
        
        private string streetAddressField;
        
        private string cityField;
        
        private string stateField;
        
        private string zipcodeField;
        
        private bool isPrimaryShippingField;
        
        private bool isActiveField;
        
        /// <remarks/>
        public int AddressId {
            get {
                return this.addressIdField;
            }
            set {
                this.addressIdField = value;
            }
        }
        
        /// <remarks/>
        public int CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        public string StreetAddress {
            get {
                return this.streetAddressField;
            }
            set {
                this.streetAddressField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Zipcode {
            get {
                return this.zipcodeField;
            }
            set {
                this.zipcodeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsPrimaryShipping {
            get {
                return this.isPrimaryShippingField;
            }
            set {
                this.isPrimaryShippingField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ACME.POS.Service.DataTypes/2007/06")]
    public partial class BillingMethod {
        
        private int billingMethodIdField;
        
        private int customerIdField;
        
        private int paymentMethodIdField;
        
        private string creditCardNumberField;
        
        private System.DateTime creditCardExpirationField;
        
        private int creditCardBillingAddressIdField;
        
        private int netTermDaysField;
        
        private bool isActiveField;
        
        /// <remarks/>
        public int BillingMethodId {
            get {
                return this.billingMethodIdField;
            }
            set {
                this.billingMethodIdField = value;
            }
        }
        
        /// <remarks/>
        public int CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        public int PaymentMethodId {
            get {
                return this.paymentMethodIdField;
            }
            set {
                this.paymentMethodIdField = value;
            }
        }
        
        /// <remarks/>
        public string CreditCardNumber {
            get {
                return this.creditCardNumberField;
            }
            set {
                this.creditCardNumberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreditCardExpiration {
            get {
                return this.creditCardExpirationField;
            }
            set {
                this.creditCardExpirationField = value;
            }
        }
        
        /// <remarks/>
        public int CreditCardBillingAddressId {
            get {
                return this.creditCardBillingAddressIdField;
            }
            set {
                this.creditCardBillingAddressIdField = value;
            }
        }
        
        /// <remarks/>
        public int NetTermDays {
            get {
                return this.netTermDaysField;
            }
            set {
                this.netTermDaysField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void GetCustomerListCompletedEventHandler(object sender, GetCustomerListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Customer[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Customer[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void SaveCustomerCompletedEventHandler(object sender, SaveCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Customer Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Customer)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591