//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACME.POS.Service.DataTypes
{


    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ACME.POS.Service.DataTypes/2007/06", IsNullable = false)]
    public class Address
    {

        private int addressId;

        private int customerId;

        private string streetAddress;

        private string city;

        private string state;

        private string zipcode;

        private bool isPrimaryShipping;

        private bool isActive;

        public int AddressId
        {
            get
            {
                return this.addressId;
            }
            set
            {
                this.addressId = value;
            }
        }

        public int CustomerId
        {
            get
            {
                return this.customerId;
            }
            set
            {
                this.customerId = value;
            }
        }

        public string StreetAddress
        {
            get
            {
                return this.streetAddress;
            }
            set
            {
                this.streetAddress = value;
            }
        }

        public string City
        {
            get
            {
                return this.city;
            }
            set
            {
                this.city = value;
            }
        }

        public string State
        {
            get
            {
                return this.state;
            }
            set
            {
                this.state = value;
            }
        }

        public string Zipcode
        {
            get
            {
                return this.zipcode;
            }
            set
            {
                this.zipcode = value;
            }
        }

        public bool IsPrimaryShipping
        {
            get
            {
                return this.isPrimaryShipping;
            }
            set
            {
                this.isPrimaryShipping = value;
            }
        }

        public bool IsActive
        {
            get
            {
                return this.isActive;
            }
            set
            {
                this.isActive = value;
            }
        }
    }
}

