//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACME.POS.Service.DataTypes
{


    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ACME.POS.Service.DataTypes/2007/06", IsNullable = false)]
    public class Customer
    {

        private int customerId;

        private string firstName;

        private string lastName;

        private System.DateTime memberSince;

        private System.DateTime birthDate;

        private ACME.POS.Service.DataTypes.Address[] addresses;

        private ACME.POS.Service.DataTypes.BillingMethod[] billingMethods;

        private bool isActive;

        private bool isModified;

        public int CustomerId
        {
            get
            {
                return this.customerId;
            }
            set
            {
                this.customerId = value;
            }
        }

        public string FirstName
        {
            get
            {
                return this.firstName;
            }
            set
            {
                this.firstName = value;
            }
        }

        public string LastName
        {
            get
            {
                return this.lastName;
            }
            set
            {
                this.lastName = value;
            }
        }

        public System.DateTime MemberSince
        {
            get
            {
                return this.memberSince;
            }
            set
            {
                this.memberSince = value;
            }
        }

        public System.DateTime BirthDate
        {
            get
            {
                return this.birthDate;
            }
            set
            {
                this.birthDate = value;
            }
        }

        public ACME.POS.Service.DataTypes.Address[] Addresses
        {
            get
            {
                return this.addresses;
            }
            set
            {
                this.addresses = value;
            }
        }

        public ACME.POS.Service.DataTypes.BillingMethod[] BillingMethods
        {
            get
            {
                return this.billingMethods;
            }
            set
            {
                this.billingMethods = value;
            }
        }

        public bool IsActive
        {
            get
            {
                return this.isActive;
            }
            set
            {
                this.isActive = value;
            }
        }

        public bool IsModified
        {
            get
            {
                return this.isModified;
            }
            set
            {
                this.isModified = value;
            }
        }
    }
}

